site_name: quickhttp
site_url: https://jayqi.github.io/quickhttp/
repo_url: https://github.com/jayqi/quickhttp/

nav:
  - Home: "index.md"
  - API Reference: "api-reference.md"

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            heading_level: 2
          selection:
            docstring_options:
              replace_admonitions: no
extra_css:
  - css/version-select.css
extra_javascript:
  - js/version-select.js
