site_name: quickhttp
site_url: https://jayqi.github.io/quickhttp/
repo_url: https://github.com/jayqi/quickhttp/

nav:
  - Home: "index.md"
  - API Reference:
      - quickhttp.exceptions: "api-reference/exceptions.md"
      - quickhttp.http_server: "api-reference/http_server.md"
  - Changelog: "changelog.md"

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  custom_dir: overrides/

extra_css:
  - css/custom_mkdocstrings.css

markdown_extensions:
  - mdx_truly_sane_lists:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
  - macros:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # Headings options
            heading_level: 2
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_heading: false
            show_category_heading: true
            # Members options
            filters: ["!^_(?!_init__)"]
            group_by_category: true
            # Docstrings options
            show_if_no_docstring: false
            # Signatures/annotation options
            show_signature_annotations: true
            # Additional options
            show_source: true
  - mike:
      alias_type: copy
      canonical_version: stable
      version_selector: true

extra:
  version:
    provider: mike
    default: stable
    alias: true
