name: release

on:
  push:
    branches:
      - release
    tags:
      - v*

jobs:
  build:
    name: Build and publish new release
    runs-on: "ubuntu-latest"
    if: github.repository == 'jayqi/quickhttp'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Get tag version
        id: tag
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Build package
        run: |
          PACKAGE_VERSION=$(poetry run quickhttp --version)
          if [ ${{ steps.tag.outputs.version }} -ne "$VERSION" ]; then exit 1; fi
          poetry run make build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          packages_dir: spongebobsay-cli/dist/
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      # - name: Publish to Production PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.3.0
      #   with:
      #     packages_dir: spongebobsay-cli/dist/
      #     user: __token__
      #     password: ${{ secrets.PYPI_PROD_TOKEN }}
      #     skip_existing: false

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tag.outputs.version }}
          release_name: v${{ steps.tag.outputs.version }}
          draft: true

      - name: Upload tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/quickhttp-${{ steps.tag.outputs.version }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/quickhttp-${{ steps.tag.outputs.version }}*.whl
