name: tests

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    # Run every Sunday
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}-slim-buster
    strategy:
      matrix:
        python-version: [3.7]
        #python-version: [3.6, 3.7, 3.8]

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        apt-get update && apt-get install make

    # - name: Lint package
    #   shell: bash
    #   run: |
    #     poetry run make lint

    - name: Test package
      shell: bash
      run: |
        poetry run make test

    - name: Test build docs
      shell: bash
      run: |
        poetry run make docs

    - name: Test building package
      shell: bash
      run: |
        poetry run make build

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
