name: tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # Run every Sunday
    - cron: "0 0 * * 0"

jobs:
  build:
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint package
        run: |
          poetry run make lint

      - name: Test package
        run: |
          poetry run make test

      - name: Test docs
        run: |
          poetry run make docs

      - name: Test building package
        run: |
          poetry run make build

      - name: Upload coverage to codecov
        if: ${{ matrix.os == 'ubuntu-latest'}}
        uses: codecov/codecov-action@v1.0.10
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
